Basic styling (Header / Footer)
Ofir-Smuha/Github-issues pull request #33
Opened 2019-01-23 06:31 UTC by Ofir-Smuha

- Header & Footer added to relevant pages
- Margins and general appearance fixed

2019-01-24 09:11 UTC, morsdyce commented
Need to fix conflicts

2019-01-24 09:22 UTC, Ofir-Smuha commented
> Need to fix conflicts

Fixed.

2019-01-24 12:11 UTC, morsdyce requested changes

2019-01-24 12:11 UTC, morsdyce commented on src/components/common/Footer.js
> +        <Link>Concatct GitHub</Link>
Got a typo in Contact

2019-01-24 12:11 UTC, morsdyce commented on src/components/issues/details/IssueDetails.js
> +      <GlobalLayout userInfo={this.props.userInfo}>
GlobalLayout should be independent. It should not be aware of the user. Only the part that is relevant to displaying user data should be aware of it.

This also leads to the header not showing until the user is loaded which is an unpleasant jump in the page.

2019-01-27 08:58 UTC, morsdyce commented on src/components/issues/new-issue/NewIssue.js
> +export default withRouter(connect(null, { addNewIssue })(NewIssue));
no need to change now but when you have multiple HoC you can use compose function from redux to write it in a way that's more readable. 

e.g:
```js
export default compose(
 withRouter,
 connect(null, { addNewIssue })
)(NewIssue)
```

2019-01-27 08:59 UTC, morsdyce approved these changes

2019-01-27 08:59 UTC, merged