Highlight selected items
Ofir-Smuha/Github-issues pull request #38
Opened 2019-01-27 13:39 UTC by Ofir-Smuha

- Highlight selected items (support multi select)
- Not supporting yet - handling selected items from URL

2019-01-28 09:02 UTC, morsdyce requested changes

2019-01-28 09:02 UTC, morsdyce commented on src/components/common/ListItem.js
> +  ${({ isSelected }) =>
instead of mentioning display twice you could do
display: `${(props) => props.isSelected ? 'block' : 'none' })`

2019-01-28 09:02 UTC, morsdyce commented on src/components/issues/SortIssues.js
> +    repoAssignees: this.props.repoAssignees,
why are you saving repoAssignees on the state?

2019-01-28 09:02 UTC, morsdyce commented on src/components/issues/SortIssues.js
> +    this.handleUrlChange(parameter, value, closeModalKey);
this looks over complicated, please explain what is the meaning of this code

2019-01-28 11:24 UTC, Ofir-Smuha commented on src/components/issues/SortIssues.js
> +    repoAssignees: this.props.repoAssignees,
Because of the functionality of is-selected. I'm passing the repoAssignees from props to state and from the state to the "ListSelect" (generic component) and manipulating the data every time an item is clicked.

2019-01-28 11:28 UTC, Ofir-Smuha commented on src/components/issues/SortIssues.js
> +    this.handleUrlChange(parameter, value, closeModalKey);
handleItemSelect function handling the item click, firstly calling the handleUrlChange for fetching the required data from Github and editing the search params in the url, then handling toggling the selected item from a specific items array (e.g repoAssignees from your comment above)

2019-01-28 18:19 UTC, morsdyce commented
Remind me to talk about this tomorrow

On Mon, Jan 28, 2019, 13:28 Ofir-Smuha <notifications@github.com wrote:

> *@Ofir-Smuha* commented on this pull request.
> ------------------------------
>
> In src/components/issues/SortIssues.js
> <https://github.com/Ofir-Smuha/Github-issues/pull/38#discussion_r251376700>
> :
>
> > @@ -199,6 +206,52 @@ class SortIssues extends Component<ConnectedProps & OwnProps, State> {
>      // Close on click
>    };
>
> +  handleItemSelect = (
> +    parameter,
> +    value,
> +    closeModalKey,
> +    itemId,
> +    itemsKey,
> +    isMultiSelect
> +  ) => {
> +    this.handleUrlChange(parameter, value, closeModalKey);
>
> handleItemSelect function handling the item click, firstly calling the
> handleUrlChange for fetching the required data from Github and editing the
> search params in the url, then handling toggling the selected item from a
> specific items array (e.g repoAssignees from your comment above)
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/Ofir-Smuha/Github-issues/pull/38#discussion_r251376700>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABlqInmiCBZru-fVR1FFWNVhgOtK-AXcks5vHt7JgaJpZM4aUuQ7>
> .
>

2019-01-30 07:48 UTC, Ofir-Smuha commented on src/components/issues/SortIssues.js
> +    this.handleUrlChange(parameter, value, closeModalKey);
Changed

2019-02-06 15:34 UTC, morsdyce approved these changes

2019-02-06 15:34 UTC, merged